GET http:/localhost:3000/movies
###

POST http:/localhost:3000/movies/3

###

PUT http:/localhost:3000/movie
###

DELETE http:/localhost:3000/movies/movieId/2

### 
GET http://localhost:3000//director

###
3,4,`5`